#!/usr/bin/env bash
set -e

usage="convert_to_pdf files"

if [ -z "$1" ]; then
  echo "${usage}"
  exit 1
fi

for file in "$@"
do
  if ! [ -f "${file}" ]; then
    echo "File ${file} does not exists or a directory. Skipping."
    continue
  fi
  name=$(basename -- "${file}")
  name="${name%.*}.pdf"

  pandoc -s -t latex --toc \
        --pdf-engine=lualatex "${file}" -o "${name}"

  echo "Converted!"
done

